name: "git merge diff"
description: "generate git merge diff between tags"
inputs:
  from:
    description: "from tag"
    required: false
    default: "prev"
  to:
    description: "to tag"
    required: false
    default: "latest"
  first-parent:
    description: "whether use --first-parent ro not"
    required: false
    default: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "git-merge"
  color: "black"
